name: API Test

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Run Docker containers
          run: |
            docker compose -f ./api_test/scripts/docker-compose.yaml up --build

        - name: Archive diffs
          if: failure()
          uses: actions/upload-artifact@v4
          with:
            name: api-test-diffs
            path: ./api_test/golang/output
